<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <IsPackable>false</IsPackable>
    <Authors>Harry Cordewener</Authors>
    <Copyright>Copyright © StateAlchemist Contributors 2026</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/HarryCordewener/StateAlchemist</PackageProjectUrl>
    <RepositoryUrl>https://github.com/HarryCordewener/StateAlchemist</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
