<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.12" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="PolySharp" Version="1.16.0" />
    <PackageVersion Include="TUnit" Version="1.66.27" />
    <PackageVersion Include="TUnit.Core" Version="1.66.27" />
    <PackageVersion Include="TUnit.Assertions" Version="1.66.27" />
    <PackageVersion Include="PublicApiGenerator" Version="11.5.4" />
    <PackageVersion Include="Verify.TUnit" Version="32.0.0" />
  </ItemGroup>
</Project>
