using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Microsoft.CodeAnalysis;
using StateAlchemist.Model;

namespace StateAlchemist.Generators;

/// <summary>
/// Writes a machine: a <c>partial</c> of the <c>[Machine]</c> class holding one field per state, a <c>switch</c> per
/// trigger kind, and one method per (transition, active leaf) with the steps of spec §6.2 written out in order.
/// Nothing it writes uses a dictionary, a hash or reflection. The output keeps to C# 7.3, so a <c>netstandard2.0</c>
/// application on its default language version compiles it.
/// </summary>
internal sealed partial class MachineEmitter
{
    private const string Rt = "global::StateAlchemist.";
    private const string ValueTaskType = "global::System.Threading.Tasks.ValueTask";
    private const string TypeType = "global::System.Type";

    private static readonly string[] ExceptionPhases = ["Guard", "Transform", "Exited", "Entered", "Completed"];

    private readonly SymbolMachine _machine;
    private readonly MachineModel _model;
    private readonly Hierarchy _hierarchy;
    private readonly Resolver _resolver;
    private readonly CodeWriter _w = new();
    private readonly string[] _stateIds;
    private readonly List<INamedTypeSymbol> _events;
    private readonly SortedSet<(int Transition, int Leaf)> _transitions = [];
    private readonly SortedSet<(int Transition, int Leaf)> _guards = [];

    private MachineEmitter(SymbolMachine machine)
    {
        _machine = machine;
        _model = machine.Model;
        _hierarchy = new Hierarchy(_model.States);
        _resolver = new Resolver(_model, _hierarchy);
        _stateIds = StateIds(_model.States);
        _events = machine.Events.OrderBy(e => e.Key, StringComparer.Ordinal).Select(e => e.Value).ToList();
    }

    /// <summary>The machine's source.</summary>
    public static string Emit(SymbolMachine machine) => new MachineEmitter(machine).Write();

    private string V => Name(_machine.Value!);

    private bool IsChecked => _model.Options.Concurrency == ConcurrencyMode.Checked;

    /// <summary>
    /// Whether the machine needs the inbox and the pump (spec §6.6, §6.10): it is <c>Serialized</c>, or has an async
    /// decision, while which it must accept events from other callers. Every other machine runs each call inline.
    /// </summary>
    private bool HasInbox => _model.Options.Concurrency == ConcurrencyMode.Serialized || _model.Transitions.Any(t => t.Decision?.DecideAsync is not null);

    private bool HasRuns => _model.Transitions.Any(t => t.IsRun);

    private string Write()
    {
        _w.Line("// <auto-generated/>");
        _w.Line($"// Generated by StateAlchemist from [Machine] {_machine.Machine.Name}. Do not edit: change the declarations instead.");
        var ns = _machine.Machine.ContainingNamespace;
        var scopes = new List<IDisposable>();
        if (ns is { IsGlobalNamespace: false })
        {
            scopes.Add(_w.Block("namespace " + ns.ToDisplayString()));
        }

        foreach (var outer in Containing(_machine.Machine))
        {
            scopes.Add(_w.Block($"partial {Keyword(outer)} {outer.Name}"));
        }

        using (_w.Block($"partial class {_machine.Machine.Name} : {Rt}IBoundaryMachine<{V}>"))
        {
            WriteStorage();
            WriteQueries();
            WriteDefinition();
            WriteDiagrams();
            WriteLifecycle();
            WriteFiring();
            WriteDispatch();
            WritePlans();
            WriteRuns();
            WriteDecisions();
            WriteTransitions();
            if (HasInbox)
            {
                WriteInbox();
            }

            WriteHooks();
        }

        for (var i = scopes.Count - 1; i >= 0; i--)
        {
            scopes[i].Dispose();
        }

        return _w.ToString();
    }

    private void WriteStorage()
    {
        _w.Line("/// <summary>The machine's states, one member each.</summary>");
        using (_w.Block("public enum StateId"))
        {
            for (var i = 0; i < _stateIds.Length; i++)
            {
                _w.Line($"/// <summary><see cref=\"{S(i)}\"/>.</summary>");
                _w.Line($"{_stateIds[i]} = {i},");
            }
        }

        _w.Line();
        for (var i = 0; i < _model.States.Count; i++)
        {
            _w.Line($"private {S(i)} {Field(i)};");
        }

        _w.Line("private StateId _leaf;");
        _w.Line($"private {Rt}MachineStatus _status;");
        _w.Line("private bool _inside;");
        _w.Line("private bool _boundaryRequested;");
        if (!HasInbox)
        {
            _w.Line("private bool _boundaryEnabled;");
        }
        _w.Line("private global::System.Threading.CancellationTokenSource _lifetime;");
        if (HasInbox)
        {
            WriteInboxStorage();
        }
        else
        {
            _w.Line("private global::System.Collections.Generic.Queue<QueuedEvent> _queue;");
            if (IsChecked)
            {
                _w.Line("private int _busy;");
            }
        }

        if (HasRuns)
        {
            _w.Line($"private {V}[] _one;");
        }

        if (_machine.Context is { } context)
        {
            _w.Line($"private readonly {Name(context)} _context;");
        }

        if (_machine.Config is { } config)
        {
            _w.Line($"private readonly {Name(config)} _config;");
        }

        _w.Line();
        var parameters = new List<string>();
        if (_machine.Context is { } c)
        {
            parameters.Add($"{Name(c)} context");
        }

        if (_machine.Config is { } g)
        {
            parameters.Add($"in {Name(g)} config");
        }

        _w.Line("/// <summary>Creates the machine in its initial state. Runs no actions: call <see cref=\"StartAsync\"/>.</summary>");
        using (_w.Block($"public {_machine.Machine.Name}({string.Join(", ", parameters)})"))
        {
            if (_machine.Context is not null)
            {
                _w.Line("_context = context;");
            }

            if (_machine.Config is not null)
            {
                _w.Line("_config = config;");
            }

            _w.Line($"_leaf = StateId.{_stateIds[_hierarchy.InitialLeaf(_hierarchy.Root)]};");
        }

        if (HasInbox)
        {
            return;
        }

        _w.Line();
        _w.Line("/// <summary>An event queued inside the machine: a tag, and the payload in the field for its type. Nothing is boxed.</summary>");
        using (_w.Block("private struct QueuedEvent"))
        {
            _w.Line("public int Tag;");
            for (var i = 0; i < _events.Count; i++)
            {
                _w.Line($"public {Name(_events[i])} E{i};");
            }

            _w.Line($"public {TypeType} Unknown;");
        }
    }

    private void WriteQueries()
    {
        _w.Line();
        _w.Line("/// <inheritdoc/>");
        _w.Line($"public {Rt}MachineStatus Status {{ get {{ return _status; }} }}");
        _w.Line();
        _w.Line("/// <summary>The active leaf.</summary>");
        _w.Line("public StateId State { get { return _leaf; } }");
        _w.Line();
        _w.Line("/// <inheritdoc/>");
        using (_w.Block($"public {TypeType} StateType"))
        {
            using (_w.Block("get"))
            {
                _w.Line("return TypeOf(_leaf);");
            }
        }

        _w.Line();
        using (_w.Block($"private static {TypeType} TypeOf(StateId state)"))
        {
            using (_w.Block("switch (state)"))
            {
                for (var i = 0; i < _model.States.Count; i++)
                {
                    _w.Line($"case StateId.{_stateIds[i]}: return typeof({S(i)});");
                }

                _w.Line("default: throw new global::System.ArgumentOutOfRangeException(\"state\");");
            }
        }

        _w.Line();
        _w.Line("/// <summary>Whether <paramref name=\"state\"/> is the active leaf or one of its ancestors.</summary>");
        using (_w.Block("public bool IsIn(StateId state)"))
        {
            using (_w.Block("switch (state)"))
            {
                for (var i = 0; i < _model.States.Count; i++)
                {
                    var test = i == _hierarchy.Root ? "true" : string.Join(" || ", _hierarchy.LeavesUnder(i).Select(l => $"_leaf == StateId.{_stateIds[l]}"));
                    _w.Line($"case StateId.{_stateIds[i]}: return {test};");
                }

                _w.Line("default: return false;");
            }
        }

        for (var i = 0; i < _model.States.Count; i++)
        {
            _w.Line();
            _w.Line($"/// <summary>A copy of <see cref=\"{S(i)}\"/>'s data, if it is active.</summary>");
            using (_w.Block($"public bool TryGet{_stateIds[i]}(out {S(i)} value)"))
            {
                _w.Line($"if (IsIn(StateId.{_stateIds[i]})) {{ value = {Field(i)}; return true; }}");
                _w.Line($"value = default({S(i)});");
                _w.Line("return false;");
            }
        }

        _w.Line();
        _w.Line("/// <inheritdoc/>");
        using (_w.Block("public bool IsIn<TState>() where TState : struct"))
        {
            for (var i = 0; i < _model.States.Count; i++)
            {
                _w.Line($"if (typeof(TState) == typeof({S(i)})) return IsIn(StateId.{_stateIds[i]});");
            }

            _w.Line("return false;");
        }

        _w.Line();
        _w.Line("/// <inheritdoc/>");
        using (_w.Block("public bool TryGetState<TState>(out TState value) where TState : struct"))
        {
            for (var i = 0; i < _model.States.Count; i++)
            {
                using (_w.Block($"if (typeof(TState) == typeof({S(i)}))"))
                {
                    _w.Line($"if (IsIn(StateId.{_stateIds[i]})) {{ value = global::System.Runtime.CompilerServices.Unsafe.As<{S(i)}, TState>(ref {Field(i)}); return true; }}");
                    _w.Line("value = default(TState);");
                    _w.Line("return false;");
                }
            }

            _w.Line("value = default(TState);");
            _w.Line("return false;");
        }
    }

    private void WriteDefinition()
    {
        _w.Line();
        _w.Line($"private static readonly {Rt}MachineDefinition s_definition = new {Rt}MachineDefinition(");
        _w.Line($"    typeof({V}),");
        _w.Line($"    new {Rt}StateDefinition[]");
        _w.Line("    {");
        foreach (var state in _model.States)
        {
            _w.Line($"        new {Rt}StateDefinition({state.Index}, typeof({S(state.Index)}), {state.Parent}, {Bool(state.IsInitial)}),");
        }

        _w.Line("    },");
        _w.Line($"    new {Rt}TransitionDefinition[]");
        _w.Line("    {");
        foreach (var t in _model.Transitions)
        {
            var usesContext = new[] { t.Guard, t.Transform }.Any(m => m is not null && m.Parameters.Any(p => p.Kind == ParameterKind.Context));
            _w.Line($"        new {Rt}TransitionDefinition({t.Index}, {Literal(t.Name)}, {t.Source}, {t.Target}, {Rt}TransitionKind.{t.Kind}, {TriggerDefinition(t.Trigger)}, " +
                    $"{t.Order}, {Bool(t.IsGuarded)}, {Bool(t.IsRun)}, {Bool(usesContext)}, {Bool(t.IsDecision)}, {OutcomeDefinitions(t)}),");
        }

        _w.Line("    });");
        _w.Line();
        _w.Line("/// <summary>The machine as data: its states, their parents, and its transitions.</summary>");
        _w.Line($"public static {Rt}MachineDefinition Definition {{ get {{ return s_definition; }} }}");
        _w.Line();
        _w.Line($"{Rt}MachineDefinition {Rt}IMachine<{V}>.Definition {{ get {{ return s_definition; }} }}");
    }

    /// <summary>
    /// A decision's outcomes, so the definition says where each one goes. Without them the states only a decision
    /// reaches have nothing pointing at them, and a diagram drawn from the definition shows them as unreachable.
    /// </summary>
    private string OutcomeDefinitions(TransitionModel transition)
    {
        var completions = transition.Decision?.Completions ?? [];
        return completions.Count == 0
            ? $"new {Rt}OutcomeDefinition[0]"
            : $"new {Rt}OutcomeDefinition[] {{ " +
              string.Join(", ", completions.Select(c => $"new {Rt}OutcomeDefinition(typeof({Name(OutcomeType(c))}), {c.Target})")) +
              " }";
    }

    private string TriggerDefinition(TriggerModel trigger) => trigger.Kind switch
    {
        MatchKind.Value => $"{Rt}TriggerDefinition.ForValue({trigger.Low})",
        MatchKind.Range => $"{Rt}TriggerDefinition.ForRange({trigger.Low}, {trigger.High})",
        MatchKind.Any => $"{Rt}TriggerDefinition.ForAny()",
        _ => $"{Rt}TriggerDefinition.ForEvent(typeof({Event(trigger.EventType!)}))",
    };

    private void WriteHooks()
    {
        _w.Line();
        _w.Line("/// <summary>After every transition. Implement it to trace; left unimplemented, the compiler removes every call.</summary>");
        _w.Line($"partial void OnTransitioned(in {Rt}TransitionInfo<{V}> transition);");
        _w.Line();
        _w.Line("/// <summary>A value nothing handles.</summary>");
        _w.Line($"partial void OnUnhandled(StateId state, {V} value);");
        foreach (var e in _events)
        {
            _w.Line();
            _w.Line($"/// <summary>A <see cref=\"{Name(e)}\"/> nothing handles.</summary>");
            _w.Line($"partial void OnUnhandled(StateId state, in {Name(e)} e);");
        }

        foreach (var phase in ExceptionPhases)
        {
            _w.Line();
            _w.Line($"/// <summary>A <c>{phase}</c> threw. Implemented, it chooses what the machine does; see <see cref=\"{Rt}ExceptionResolution\"/>.</summary>");
            _w.Line($"partial void On{phase}Exception(global::System.Exception exception, in {Rt}TransitionInfo<{V}> transition, ref {Rt}ExceptionResolution resolution);");
        }
    }

    /// <summary>Whether the application implements a hook: only then is its <c>try</c>/<c>catch</c> written (spec §6.9).</summary>
    private bool Implements(string hook) => _machine.Machine.GetMembers(hook).OfType<IMethodSymbol>().Any();

    private string S(int state) => Name(_machine.StateTypes[state]);

    private static string Field(int state) => "_s" + state.ToString(CultureInfo.InvariantCulture);

    private static string Name(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private string Event(string metadataName) => Name(_machine.Events[metadataName]);

    private int EventTag(string metadataName) => _events.FindIndex(e => SymbolModelBuilder.MetadataName(e) == metadataName);

    private string Owner(MethodModel method) => Name(_machine.Methods[method].ContainingType) + "." + method.Name;

    private static string Bool(bool value) => value ? "true" : "false";

    /// <summary>A C# string literal of <paramref name="text"/>, newlines included: a diagram is many lines.</summary>
    private static string Literal(string text) => "\"" + text
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r", string.Empty)
        .Replace("\n", "\\n") + "\"";

    private static IEnumerable<INamedTypeSymbol> Containing(INamedTypeSymbol type)
    {
        var chain = new List<INamedTypeSymbol>();
        for (var outer = type.ContainingType; outer is not null; outer = outer.ContainingType)
        {
            chain.Insert(0, outer);
        }

        return chain;
    }

    private static string Keyword(INamedTypeSymbol type) => (type.IsRecord, type.TypeKind) switch
    {
        (true, TypeKind.Struct) => "record struct",
        (true, _) => "record",
        (_, TypeKind.Struct) => "struct",
        (_, TypeKind.Interface) => "interface",
        _ => "class",
    };

    /// <summary>Each state's <c>StateId</c> member: its short name, or its full name when two states share a short name.</summary>
    private static string[] StateIds(IReadOnlyList<StateModel> states)
    {
        var shared = new HashSet<string>(states.GroupBy(s => s.Name).Where(g => g.Count() > 1).Select(g => g.Key));
        return states.Select(s => shared.Contains(s.Name) ? s.TypeName.Replace('.', '_').Replace('+', '_') : s.Name).ToArray();
    }
}
